### ISSUE TITLE
Lints - Update analysis_options.yaml

### ISSUE THREAD

**Issue by redDwarf03** [archethic-foundation/yubidart#3]
Increase the nb of rules
Reuse https://github.com/archethic-foundation/libdart/blob/dev/analysis_options.yaml

**Comment by Dinokojt7** [comment]
Hi @redDwarf03 I hope you're doing well on that side. I am contacting you because I would appreciate if you could mentor me or give me help on my project, I just have one task that needs me to drill down properties and I've been struggling with it for so long also I'm not getting the right kind of feedback from SO. Thanks for reading this

**Comment by redDwarf03** [comment]
Hello. could you contact me with telegram with the same github of name's profile. thx

**Comment by Dinokojt7** [comment]
Hi it's okay I'll do just that thanks.
